INSERT INTO country (id, name, code, region_id) VALUES (1, 'Afghanistan', 'AF', 3);
INSERT INTO country (id, name, code, region_id) VALUES (2, 'Aland Islands', 'AX', 4);
INSERT INTO country (id, name, code, region_id) VALUES (3, 'Albania', 'AL', 4);
INSERT INTO country (id, name, code, region_id) VALUES (4, 'Algeria', 'DZ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (5, 'American Samoa', 'AS', 5);
INSERT INTO country (id, name, code, region_id) VALUES (6, 'Andorra', 'AD', 4);
INSERT INTO country (id, name, code, region_id) VALUES (7, 'Angola', 'AO', 1);
INSERT INTO country (id, name, code, region_id) VALUES (8, 'Anguilla', 'AI', 2);
INSERT INTO country (id, name, code, region_id) VALUES (9, 'Antarctica', 'AQ', 6);
INSERT INTO country (id, name, code, region_id) VALUES (10, 'Antigua and Barbuda', 'AG', 2);
INSERT INTO country (id, name, code, region_id) VALUES (11, 'Argentina', 'AR', 2);
INSERT INTO country (id, name, code, region_id) VALUES (12, 'Armenia', 'AM', 3);
INSERT INTO country (id, name, code, region_id) VALUES (13, 'Aruba', 'AW', 2);
INSERT INTO country (id, name, code, region_id) VALUES (14, 'Australia', 'AU', 5);
INSERT INTO country (id, name, code, region_id) VALUES (15, 'Austria', 'AT', 4);
INSERT INTO country (id, name, code, region_id) VALUES (16, 'Azerbaijan', 'AZ', 3);
INSERT INTO country (id, name, code, region_id) VALUES (17, 'The Bahamas', 'BS', 2);
INSERT INTO country (id, name, code, region_id) VALUES (18, 'Bahrain', 'BH', 3);
INSERT INTO country (id, name, code, region_id) VALUES (19, 'Bangladesh', 'BD', 3);
INSERT INTO country (id, name, code, region_id) VALUES (20, 'Barbados', 'BB', 2);
INSERT INTO country (id, name, code, region_id) VALUES (21, 'Belarus', 'BY', 4);
INSERT INTO country (id, name, code, region_id) VALUES (22, 'Belgium', 'BE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (23, 'Belize', 'BZ', 2);
INSERT INTO country (id, name, code, region_id) VALUES (24, 'Benin', 'BJ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (25, 'Bermuda', 'BM', 2);
INSERT INTO country (id, name, code, region_id) VALUES (26, 'Bhutan', 'BT', 3);
INSERT INTO country (id, name, code, region_id) VALUES (27, 'Bolivia', 'BO', 2);
INSERT INTO country (id, name, code, region_id) VALUES (28, 'Bosnia and Herzegovina', 'BA', 4);
INSERT INTO country (id, name, code, region_id) VALUES (29, 'Botswana', 'BW', 1);
INSERT INTO country (id, name, code, region_id) VALUES (30, 'Bouvet Island', 'BV', NULL);
INSERT INTO country (id, name, code, region_id) VALUES (31, 'Brazil', 'BR', 2);
INSERT INTO country (id, name, code, region_id) VALUES (32, 'British Indian Ocean Territory', 'IO', 1);
INSERT INTO country (id, name, code, region_id) VALUES (33, 'Brunei', 'BN', 3);
INSERT INTO country (id, name, code, region_id) VALUES (34, 'Bulgaria', 'BG', 4);
INSERT INTO country (id, name, code, region_id) VALUES (35, 'Burkina Faso', 'BF', 1);
INSERT INTO country (id, name, code, region_id) VALUES (36, 'Burundi', 'BI', 1);
INSERT INTO country (id, name, code, region_id) VALUES (37, 'Cambodia', 'KH', 3);
INSERT INTO country (id, name, code, region_id) VALUES (38, 'Cameroon', 'CM', 1);
INSERT INTO country (id, name, code, region_id) VALUES (39, 'Canada', 'CA', 2);
INSERT INTO country (id, name, code, region_id) VALUES (40, 'Cape Verde', 'CV', 1);
INSERT INTO country (id, name, code, region_id) VALUES (41, 'Cayman Islands', 'KY', 2);
INSERT INTO country (id, name, code, region_id) VALUES (42, 'Central African Republic', 'CF', 1);
INSERT INTO country (id, name, code, region_id) VALUES (43, 'Chad', 'TD', 1);
INSERT INTO country (id, name, code, region_id) VALUES (44, 'Chile', 'CL', 2);
INSERT INTO country (id, name, code, region_id) VALUES (45, 'China', 'CN', 3);
INSERT INTO country (id, name, code, region_id) VALUES (46, 'Christmas Island', 'CX', 5);
INSERT INTO country (id, name, code, region_id) VALUES (47, 'Cocos (Keeling) Islands', 'CC', 5);
INSERT INTO country (id, name, code, region_id) VALUES (48, 'Colombia', 'CO', 2);
INSERT INTO country (id, name, code, region_id) VALUES (49, 'Comoros', 'KM', 1);
INSERT INTO country (id, name, code, region_id) VALUES (50, 'Congo', 'CG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (51, 'Democratic Republic of the Congo', 'CD', 1);
INSERT INTO country (id, name, code, region_id) VALUES (52, 'Cook Islands', 'CK', 5);
INSERT INTO country (id, name, code, region_id) VALUES (53, 'Costa Rica', 'CR', 2);
INSERT INTO country (id, name, code, region_id) VALUES (54, 'Cote D''Ivoire (Ivory Coast)', 'CI', 1);
INSERT INTO country (id, name, code, region_id) VALUES (55, 'Croatia', 'HR', 4);
INSERT INTO country (id, name, code, region_id) VALUES (56, 'Cuba', 'CU', 2);
INSERT INTO country (id, name, code, region_id) VALUES (57, 'Cyprus', 'CY', 4);
INSERT INTO country (id, name, code, region_id) VALUES (58, 'Czech Republic', 'CZ', 4);
INSERT INTO country (id, name, code, region_id) VALUES (59, 'Denmark', 'DK', 4);
INSERT INTO country (id, name, code, region_id) VALUES (60, 'Djibouti', 'DJ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (61, 'Dominica', 'DM', 2);
INSERT INTO country (id, name, code, region_id) VALUES (62, 'Dominican Republic', 'DO', 2);
INSERT INTO country (id, name, code, region_id) VALUES (63, 'Timor-Leste', 'TL', 3);
INSERT INTO country (id, name, code, region_id) VALUES (64, 'Ecuador', 'EC', 2);
INSERT INTO country (id, name, code, region_id) VALUES (65, 'Egypt', 'EG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (66, 'El Salvador', 'SV', 2);
INSERT INTO country (id, name, code, region_id) VALUES (67, 'Equatorial Guinea', 'GQ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (68, 'Eritrea', 'ER', 1);
INSERT INTO country (id, name, code, region_id) VALUES (69, 'Estonia', 'EE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (70, 'Ethiopia', 'ET', 1);
INSERT INTO country (id, name, code, region_id) VALUES (71, 'Falkland Islands', 'FK', 2);
INSERT INTO country (id, name, code, region_id) VALUES (72, 'Faroe Islands', 'FO', 4);
INSERT INTO country (id, name, code, region_id) VALUES (73, 'Fiji Islands', 'FJ', 5);
INSERT INTO country (id, name, code, region_id) VALUES (74, 'Finland', 'FI', 4);
INSERT INTO country (id, name, code, region_id) VALUES (75, 'France', 'FR', 4);
INSERT INTO country (id, name, code, region_id) VALUES (76, 'French Guiana', 'GF', 2);
INSERT INTO country (id, name, code, region_id) VALUES (77, 'French Polynesia', 'PF', 5);
INSERT INTO country (id, name, code, region_id) VALUES (78, 'French Southern Territories', 'TF', 1);
INSERT INTO country (id, name, code, region_id) VALUES (79, 'Gabon', 'GA', 1);
INSERT INTO country (id, name, code, region_id) VALUES (80, 'Gambia The', 'GM', 1);
INSERT INTO country (id, name, code, region_id) VALUES (81, 'Georgia', 'GE', 3);
INSERT INTO country (id, name, code, region_id) VALUES (82, 'Germany', 'DE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (83, 'Ghana', 'GH', 1);
INSERT INTO country (id, name, code, region_id) VALUES (84, 'Gibraltar', 'GI', 4);
INSERT INTO country (id, name, code, region_id) VALUES (85, 'Greece', 'GR', 4);
INSERT INTO country (id, name, code, region_id) VALUES (86, 'Greenland', 'GL', 2);
INSERT INTO country (id, name, code, region_id) VALUES (87, 'Grenada', 'GD', 2);
INSERT INTO country (id, name, code, region_id) VALUES (88, 'Guadeloupe', 'GP', 2);
INSERT INTO country (id, name, code, region_id) VALUES (89, 'Guam', 'GU', 5);
INSERT INTO country (id, name, code, region_id) VALUES (90, 'Guatemala', 'GT', 2);
INSERT INTO country (id, name, code, region_id) VALUES (91, 'Guernsey and Alderney', 'GG', 4);
INSERT INTO country (id, name, code, region_id) VALUES (92, 'Guinea', 'GN', 1);
INSERT INTO country (id, name, code, region_id) VALUES (93, 'Guinea-Bissau', 'GW', 1);
INSERT INTO country (id, name, code, region_id) VALUES (94, 'Guyana', 'GY', 2);
INSERT INTO country (id, name, code, region_id) VALUES (95, 'Haiti', 'HT', 2);
INSERT INTO country (id, name, code, region_id) VALUES (96, 'Heard Island and McDonald Islands', 'HM', NULL);
INSERT INTO country (id, name, code, region_id) VALUES (97, 'Honduras', 'HN', 2);
INSERT INTO country (id, name, code, region_id) VALUES (98, 'Hong Kong S.A.R.', 'HK', 3);
INSERT INTO country (id, name, code, region_id) VALUES (99, 'Hungary', 'HU', 4);
INSERT INTO country (id, name, code, region_id) VALUES (100, 'Iceland', 'IS', 4);
INSERT INTO country (id, name, code, region_id) VALUES (101, 'India', 'IN', 3);
INSERT INTO country (id, name, code, region_id) VALUES (102, 'Indonesia', 'ID', 3);
INSERT INTO country (id, name, code, region_id) VALUES (103, 'Iran', 'IR', 3);
INSERT INTO country (id, name, code, region_id) VALUES (104, 'Iraq', 'IQ', 3);
INSERT INTO country (id, name, code, region_id) VALUES (105, 'Ireland', 'IE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (106, 'Israel', 'IL', 3);
INSERT INTO country (id, name, code, region_id) VALUES (107, 'Italy', 'IT', 4);
INSERT INTO country (id, name, code, region_id) VALUES (108, 'Jamaica', 'JM', 2);
INSERT INTO country (id, name, code, region_id) VALUES (109, 'Japan', 'JP', 3);
INSERT INTO country (id, name, code, region_id) VALUES (110, 'Jersey', 'JE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (111, 'Jordan', 'JO', 3);
INSERT INTO country (id, name, code, region_id) VALUES (112, 'Kazakhstan', 'KZ', 3);
INSERT INTO country (id, name, code, region_id) VALUES (113, 'Kenya', 'KE', 1);
INSERT INTO country (id, name, code, region_id) VALUES (114, 'Kiribati', 'KI', 5);
INSERT INTO country (id, name, code, region_id) VALUES (115, 'North Korea', 'KP', 3);
INSERT INTO country (id, name, code, region_id) VALUES (116, 'South Korea', 'KR', 3);
INSERT INTO country (id, name, code, region_id) VALUES (117, 'Kuwait', 'KW', 3);
INSERT INTO country (id, name, code, region_id) VALUES (118, 'Kyrgyzstan', 'KG', 3);
INSERT INTO country (id, name, code, region_id) VALUES (119, 'Laos', 'LA', 3);
INSERT INTO country (id, name, code, region_id) VALUES (120, 'Latvia', 'LV', 4);
INSERT INTO country (id, name, code, region_id) VALUES (121, 'Lebanon', 'LB', 3);
INSERT INTO country (id, name, code, region_id) VALUES (122, 'Lesotho', 'LS', 1);
INSERT INTO country (id, name, code, region_id) VALUES (123, 'Liberia', 'LR', 1);
INSERT INTO country (id, name, code, region_id) VALUES (124, 'Libya', 'LY', 1);
INSERT INTO country (id, name, code, region_id) VALUES (125, 'Liechtenstein', 'LI', 4);
INSERT INTO country (id, name, code, region_id) VALUES (126, 'Lithuania', 'LT', 4);
INSERT INTO country (id, name, code, region_id) VALUES (127, 'Luxembourg', 'LU', 4);
INSERT INTO country (id, name, code, region_id) VALUES (128, 'Macau S.A.R.', 'MO', 3);
INSERT INTO country (id, name, code, region_id) VALUES (129, 'North Macedonia', 'MK', 4);
INSERT INTO country (id, name, code, region_id) VALUES (130, 'Madagascar', 'MG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (131, 'Malawi', 'MW', 1);
INSERT INTO country (id, name, code, region_id) VALUES (132, 'Malaysia', 'MY', 3);
INSERT INTO country (id, name, code, region_id) VALUES (133, 'Maldives', 'MV', 3);
INSERT INTO country (id, name, code, region_id) VALUES (134, 'Mali', 'ML', 1);
INSERT INTO country (id, name, code, region_id) VALUES (135, 'Malta', 'MT', 4);
INSERT INTO country (id, name, code, region_id) VALUES (136, 'Man (Isle of)', 'IM', 4);
INSERT INTO country (id, name, code, region_id) VALUES (137, 'Marshall Islands', 'MH', 5);
INSERT INTO country (id, name, code, region_id) VALUES (138, 'Martinique', 'MQ', 2);
INSERT INTO country (id, name, code, region_id) VALUES (139, 'Mauritania', 'MR', 1);
INSERT INTO country (id, name, code, region_id) VALUES (140, 'Mauritius', 'MU', 1);
INSERT INTO country (id, name, code, region_id) VALUES (141, 'Mayotte', 'YT', 1);
INSERT INTO country (id, name, code, region_id) VALUES (142, 'Mexico', 'MX', 2);
INSERT INTO country (id, name, code, region_id) VALUES (143, 'Micronesia', 'FM', 5);
INSERT INTO country (id, name, code, region_id) VALUES (144, 'Moldova', 'MD', 4);
INSERT INTO country (id, name, code, region_id) VALUES (145, 'Monaco', 'MC', 4);
INSERT INTO country (id, name, code, region_id) VALUES (146, 'Mongolia', 'MN', 3);
INSERT INTO country (id, name, code, region_id) VALUES (147, 'Montenegro', 'ME', 4);
INSERT INTO country (id, name, code, region_id) VALUES (148, 'Montserrat', 'MS', 2);
INSERT INTO country (id, name, code, region_id) VALUES (149, 'Morocco', 'MA', 1);
INSERT INTO country (id, name, code, region_id) VALUES (150, 'Mozambique', 'MZ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (151, 'Myanmar', 'MM', 3);
INSERT INTO country (id, name, code, region_id) VALUES (152, 'Namibia', 'NA', 1);
INSERT INTO country (id, name, code, region_id) VALUES (153, 'Nauru', 'NR', 5);
INSERT INTO country (id, name, code, region_id) VALUES (154, 'Nepal', 'NP', 3);
INSERT INTO country (id, name, code, region_id) VALUES (155, 'Bonaire, Sint Eustatius and Saba', 'BQ', 2);
INSERT INTO country (id, name, code, region_id) VALUES (156, 'Netherlands', 'NL', 4);
INSERT INTO country (id, name, code, region_id) VALUES (157, 'New Caledonia', 'NC', 5);
INSERT INTO country (id, name, code, region_id) VALUES (158, 'New Zealand', 'NZ', 5);
INSERT INTO country (id, name, code, region_id) VALUES (159, 'Nicaragua', 'NI', 2);
INSERT INTO country (id, name, code, region_id) VALUES (160, 'Niger', 'NE', 1);
INSERT INTO country (id, name, code, region_id) VALUES (161, 'Nigeria', 'NG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (162, 'Niue', 'NU', 5);
INSERT INTO country (id, name, code, region_id) VALUES (163, 'Norfolk Island', 'NF', 5);
INSERT INTO country (id, name, code, region_id) VALUES (164, 'Northern Mariana Islands', 'MP', 5);
INSERT INTO country (id, name, code, region_id) VALUES (165, 'Norway', 'NO', 4);
INSERT INTO country (id, name, code, region_id) VALUES (166, 'Oman', 'OM', 3);
INSERT INTO country (id, name, code, region_id) VALUES (167, 'Pakistan', 'PK', 3);
INSERT INTO country (id, name, code, region_id) VALUES (168, 'Palau', 'PW', 5);
INSERT INTO country (id, name, code, region_id) VALUES (169, 'Palestinian Territory Occupied', 'PS', 3);
INSERT INTO country (id, name, code, region_id) VALUES (170, 'Panama', 'PA', 2);
INSERT INTO country (id, name, code, region_id) VALUES (171, 'Papua New Guinea', 'PG', 5);
INSERT INTO country (id, name, code, region_id) VALUES (172, 'Paraguay', 'PY', 2);
INSERT INTO country (id, name, code, region_id) VALUES (173, 'Peru', 'PE', 2);
INSERT INTO country (id, name, code, region_id) VALUES (174, 'Philippines', 'PH', 3);
INSERT INTO country (id, name, code, region_id) VALUES (175, 'Pitcairn Island', 'PN', 5);
INSERT INTO country (id, name, code, region_id) VALUES (176, 'Poland', 'PL', 4);
INSERT INTO country (id, name, code, region_id) VALUES (177, 'Portugal', 'PT', 4);
INSERT INTO country (id, name, code, region_id) VALUES (178, 'Puerto Rico', 'PR', 2);
INSERT INTO country (id, name, code, region_id) VALUES (179, 'Qatar', 'QA', 3);
INSERT INTO country (id, name, code, region_id) VALUES (180, 'Reunion', 'RE', 1);
INSERT INTO country (id, name, code, region_id) VALUES (181, 'Romania', 'RO', 4);
INSERT INTO country (id, name, code, region_id) VALUES (182, 'Russia', 'RU', 4);
INSERT INTO country (id, name, code, region_id) VALUES (183, 'Rwanda', 'RW', 1);
INSERT INTO country (id, name, code, region_id) VALUES (184, 'Saint Helena', 'SH', 1);
INSERT INTO country (id, name, code, region_id) VALUES (185, 'Saint Kitts and Nevis', 'KN', 2);
INSERT INTO country (id, name, code, region_id) VALUES (186, 'Saint Lucia', 'LC', 2);
INSERT INTO country (id, name, code, region_id) VALUES (187, 'Saint Pierre and Miquelon', 'PM', 2);
INSERT INTO country (id, name, code, region_id) VALUES (188, 'Saint Vincent and the Grenadines', 'VC', 2);
INSERT INTO country (id, name, code, region_id) VALUES (189, 'Saint-Barthelemy', 'BL', 2);
INSERT INTO country (id, name, code, region_id) VALUES (190, 'Saint-Martin (French part)', 'MF', 2);
INSERT INTO country (id, name, code, region_id) VALUES (191, 'Samoa', 'WS', 5);
INSERT INTO country (id, name, code, region_id) VALUES (192, 'San Marino', 'SM', 4);
INSERT INTO country (id, name, code, region_id) VALUES (193, 'Sao Tome and Principe', 'ST', 1);
INSERT INTO country (id, name, code, region_id) VALUES (194, 'Saudi Arabia', 'SA', 3);
INSERT INTO country (id, name, code, region_id) VALUES (195, 'Senegal', 'SN', 1);
INSERT INTO country (id, name, code, region_id) VALUES (196, 'Serbia', 'RS', 4);
INSERT INTO country (id, name, code, region_id) VALUES (197, 'Seychelles', 'SC', 1);
INSERT INTO country (id, name, code, region_id) VALUES (198, 'Sierra Leone', 'SL', 1);
INSERT INTO country (id, name, code, region_id) VALUES (199, 'Singapore', 'SG', 3);
INSERT INTO country (id, name, code, region_id) VALUES (200, 'Slovakia', 'SK', 4);
INSERT INTO country (id, name, code, region_id) VALUES (201, 'Slovenia', 'SI', 4);
INSERT INTO country (id, name, code, region_id) VALUES (202, 'Solomon Islands', 'SB', 5);
INSERT INTO country (id, name, code, region_id) VALUES (203, 'Somalia', 'SO', 1);
INSERT INTO country (id, name, code, region_id) VALUES (204, 'South Africa', 'ZA', 1);
INSERT INTO country (id, name, code, region_id) VALUES (205, 'South Georgia', 'GS', 2);
INSERT INTO country (id, name, code, region_id) VALUES (206, 'South Sudan', 'SS', 1);
INSERT INTO country (id, name, code, region_id) VALUES (207, 'Spain', 'ES', 4);
INSERT INTO country (id, name, code, region_id) VALUES (208, 'Sri Lanka', 'LK', 3);
INSERT INTO country (id, name, code, region_id) VALUES (209, 'Sudan', 'SD', 1);
INSERT INTO country (id, name, code, region_id) VALUES (210, 'Suriname', 'SR', 2);
INSERT INTO country (id, name, code, region_id) VALUES (211, 'Svalbard and Jan Mayen Islands', 'SJ', 4);
INSERT INTO country (id, name, code, region_id) VALUES (212, 'Eswatini', 'SZ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (213, 'Sweden', 'SE', 4);
INSERT INTO country (id, name, code, region_id) VALUES (214, 'Switzerland', 'CH', 4);
INSERT INTO country (id, name, code, region_id) VALUES (215, 'Syria', 'SY', 3);
INSERT INTO country (id, name, code, region_id) VALUES (216, 'Taiwan', 'TW', 3);
INSERT INTO country (id, name, code, region_id) VALUES (217, 'Tajikistan', 'TJ', 3);
INSERT INTO country (id, name, code, region_id) VALUES (218, 'Tanzania', 'TZ', 1);
INSERT INTO country (id, name, code, region_id) VALUES (219, 'Thailand', 'TH', 3);
INSERT INTO country (id, name, code, region_id) VALUES (220, 'Togo', 'TG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (221, 'Tokelau', 'TK', 5);
INSERT INTO country (id, name, code, region_id) VALUES (222, 'Tonga', 'TO', 5);
INSERT INTO country (id, name, code, region_id) VALUES (223, 'Trinidad and Tobago', 'TT', 2);
INSERT INTO country (id, name, code, region_id) VALUES (224, 'Tunisia', 'TN', 1);
INSERT INTO country (id, name, code, region_id) VALUES (225, 'Turkey', 'TR', 3);
INSERT INTO country (id, name, code, region_id) VALUES (226, 'Turkmenistan', 'TM', 3);
INSERT INTO country (id, name, code, region_id) VALUES (227, 'Turks and Caicos Islands', 'TC', 2);
INSERT INTO country (id, name, code, region_id) VALUES (228, 'Tuvalu', 'TV', 5);
INSERT INTO country (id, name, code, region_id) VALUES (229, 'Uganda', 'UG', 1);
INSERT INTO country (id, name, code, region_id) VALUES (230, 'Ukraine', 'UA', 4);
INSERT INTO country (id, name, code, region_id) VALUES (231, 'United Arab Emirates', 'AE', 3);
INSERT INTO country (id, name, code, region_id) VALUES (232, 'United Kingdom', 'GB', 4);
INSERT INTO country (id, name, code, region_id) VALUES (233, 'United States', 'US', 2);
INSERT INTO country (id, name, code, region_id) VALUES (234, 'United States Minor Outlying Islands', 'UM', 2);
INSERT INTO country (id, name, code, region_id) VALUES (235, 'Uruguay', 'UY', 2);
INSERT INTO country (id, name, code, region_id) VALUES (236, 'Uzbekistan', 'UZ', 3);
INSERT INTO country (id, name, code, region_id) VALUES (237, 'Vanuatu', 'VU', 5);
INSERT INTO country (id, name, code, region_id) VALUES (238, 'Vatican City State (Holy See)', 'VA', 4);
INSERT INTO country (id, name, code, region_id) VALUES (239, 'Venezuela', 'VE', 2);
INSERT INTO country (id, name, code, region_id) VALUES (240, 'Vietnam', 'VN', 3);
INSERT INTO country (id, name, code, region_id) VALUES (241, 'Virgin Islands (British)', 'VG', 2);
INSERT INTO country (id, name, code, region_id) VALUES (242, 'Virgin Islands (US)', 'VI', 2);
INSERT INTO country (id, name, code, region_id) VALUES (243, 'Wallis and Futuna Islands', 'WF', 5);
INSERT INTO country (id, name, code, region_id) VALUES (244, 'Western Sahara', 'EH', 1);
INSERT INTO country (id, name, code, region_id) VALUES (245, 'Yemen', 'YE', 3);
INSERT INTO country (id, name, code, region_id) VALUES (246, 'Zambia', 'ZM', 1);
INSERT INTO country (id, name, code, region_id) VALUES (247, 'Zimbabwe', 'ZW', 1);
INSERT INTO country (id, name, code, region_id) VALUES (248, 'Kosovo', 'XK', 4);
INSERT INTO country (id, name, code, region_id) VALUES (249, 'Curaçao', 'CW', 2);
INSERT INTO country (id, name, code, region_id) VALUES (250, 'Sint Maarten (Dutch part)', 'SX', 2);